### ISSUE TITLE
英文文本分类

### ISSUE THREAD

**Issue by yufengjiao** [ningchaoar/UnsupervisedTextClassification#2]
您好，请问您的代码是否适用于英文文本呢？

**Comment by ningchaoar** [comment]
可以，对于任意语言的文本，只要改一下分词部分的逻辑(utils.word_segment)即可，分词完成后文本被向量化就和语言无关了。不过我给出的相关参数都是适配给定数据集的，不同的数据集可能需要您自己调一调以达到最好效果。
